development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://ram-family12345678@redis-18355.c44.us-east-1-2.ec2.cloud.redislabs.com:18355
  channel_prefix: my-family_production
