# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: my-family-dev
  username: root
  password:
  host: localhost


test:
  adapter: mysql2
  encoding: utf8
  database: my-family-test
  username: root
  password:
  host: localhost


production:
  adapter: mysql2
  encoding: utf8
  database: my-family-production
  username: root
  password:
  host: localhost
